version: '3.7'

services:

  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - ./data:/data
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=app
      - DB_PORT=tcp://app:9999

