version: '3.7'

services:

  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - ./data:/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=app


